"""
HTML template renderer for COREP templates.
Converts structured JSON output to formatted HTML tables.
"""
from typing import Dict, Any
from jinja2 import Template


# HTML template for C 01.00 (Own Funds)
C01_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>COREP C 01.00 - Own Funds</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }
        .header {
            background-color: #003d5c;
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0 0;
            font-size: 14px;
        }
        .warnings {
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin-bottom: 20px;
        }
        .warnings h3 {
            margin-top: 0;
            color: #856404;
        }
        .warnings ul {
            margin: 10px 0;
            padding-left: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #003d5c;
            color: white;
            font-weight: bold;
        }
        .row-code {
            font-weight: bold;
            background-color: #f8f9fa;
            width: 80px;
        }
        .metric-name {
            min-width: 300px;
        }
        .value {
            text-align: right;
            font-family: 'Courier New', monospace;
            width: 150px;
        }
        .status {
            text-align: center;
            width: 100px;
        }
        .status-populated {
            background-color: #d4edda;
            color: #155724;
        }
        .status-missing {
            background-color: #f8d7da;
            color: #721c24;
        }
        .status-inconsistent {
            background-color: #fff3cd;
            color: #856404;
        }
        .tooltip {
            position: relative;
            display: inline-block;
            cursor: help;
        }
        .tooltip .tooltiptext {
            visibility: hidden;
            width: 300px;
            background-color: #333;
            color: #fff;
            text-align: left;
            border-radius: 6px;
            padding: 10px;
            position: absolute;
            z-index: 1;
            bottom: 125%;
            left: 50%;
            margin-left: -150px;
            opacity: 0;
            transition: opacity 0.3s;
            font-size: 12px;
            line-height: 1.4;
        }
        .tooltip .tooltiptext::after {
            content: "";
            position: absolute;
            top: 100%;
            left: 50%;
            margin-left: -5px;
            border-width: 5px;
            border-style: solid;
            border-color: #333 transparent transparent transparent;
        }
        .tooltip:hover .tooltiptext {
            visibility: visible;
            opacity: 1;
        }
        .sources {
            font-size: 11px;
            color: #666;
            margin-top: 5px;
        }
        .footer {
            margin-top: 20px;
            padding: 15px;
            background-color: white;
            border-top: 3px solid #003d5c;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>COREP C 01.00 - Own Funds</h1>
        <p>Generated by PRA COREP Reporting Assistant</p>
    </div>

    {% if validation_warnings %}
    <div class="warnings">
        <h3>⚠️ Validation Warnings</h3>
        <ul>
        {% for warning in validation_warnings %}
            <li>{{ warning }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}

    <table>
        <thead>
            <tr>
                <th>Row</th>
                <th>Metric</th>
                <th>Value ({{ currency }})</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        {% for field in fields %}
            <tr>
                <td class="row-code">{{ field.row }}</td>
                <td class="metric-name">
                    <div class="tooltip">
                        {{ field.metric_name }}
                        <span class="tooltiptext">
                            <strong>Justification:</strong><br>
                            {{ field.justification }}
                            {% if field.source_paragraphs %}
                            <br><br><strong>Sources:</strong><br>
                            {{ field.source_paragraphs | join(', ') }}
                            {% endif %}
                        </span>
                    </div>
                    {% if field.source_paragraphs %}
                    <div class="sources">📚 {{ field.source_paragraphs | join(', ') }}</div>
                    {% endif %}
                </td>
                <td class="value">
                    {% if field.value is not none %}
                        {{ "{:,.2f}".format(field.value) }}
                    {% else %}
                        <em>N/A</em>
                    {% endif %}
                </td>
                <td class="status status-{{ field.status }}">
                    {{ field.status | upper }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="footer">
        <p><strong>Legend:</strong></p>
        <p><span style="background-color: #d4edda; padding: 3px 8px;">POPULATED</span> - Field successfully populated from scenario</p>
        <p><span style="background-color: #f8d7da; padding: 3px 8px;">MISSING</span> - Insufficient information in scenario</p>
        <p><span style="background-color: #fff3cd; padding: 3px 8px;">INCONSISTENT</span> - Data contradictions detected</p>
        <p style="margin-top: 10px; font-style: italic;">Hover over metric names to see detailed justifications and regulatory sources.</p>
    </div>
</body>
</html>
"""


def render_corep_html(corep_output: Dict[str, Any]) -> str:
    """
    Render COREP output as HTML table.
    
    Args:
        corep_output: Dictionary containing COREP fields and metadata
    
    Returns:
        HTML string with formatted COREP template
    """
    template = Template(C01_HTML_TEMPLATE)
    
    # Extract currency from first field or default to GBP
    currency = "GBP"
    if corep_output.get("fields") and len(corep_output["fields"]) > 0:
        currency = corep_output["fields"][0].get("currency", "GBP")
    
    html = template.render(
        fields=corep_output.get("fields", []),
        validation_warnings=corep_output.get("validation_warnings", []),
        currency=currency
    )
    
    return html
